name: Docker Image CI - Code-Julia

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
         cd julia
         docker build . --file Dockerfile --tag code-julia:$(date +%s)
